[toolchain]
# Check https://www.fastly.com/documentation/guides/compute/developer-guides/rust/#rust-language-support for the latest supported Rust version.
channel = "1.91.1"
targets = ["wasm32-wasip1"]
